# Generated by Django 4.1.1 on 2023-02-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_category_offer_id_alter_coupon_id_and_more"),
        ("orders", "0015_alter_banner_id_alter_banner_is_selected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_product",
                to="store.product",
            ),
        ),
    ]
